spring:
    application:
        name: Central_Kitchens_and_Franchise_Store_BE

    datasource:
        url: jdbc:mysql://localhost:3306/CENTRAL_KITCHEN_MANGEMENT
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: false

server:
  port: 8081
  servlet:
    context-path: /

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    group-configs:
      - group: Ingredient Management
        paths-to-match: /api/ingredients/**
        display-name: Ingredient APIs
      - group: Recipe Management
        paths-to-match: /api/recipes/**
        display-name: Recipe APIs
      - group: Food Management
        paths-to-match: /api/foods/**
        display-name: Food APIs
      - group: Franchise Store Management
        paths-to-match: /api/stores/**
        display-name: Franchise Store APIs
      - group: Order Management
        paths-to-match: /api/orders/**
        display-name: Order APIs
      - group: Shipment Management
        paths-to-match: /api/shipments/**
        display-name: Shipment APIs
      - group: Payment Management
        paths-to-match: /api/payments/**
        display-name: Payment APIs
      - group: Feedback Management
        paths-to-match: /api/feedbacks/**
        display-name: Feedback APIs


